spring.application.name=springboot-ai
logging.pattern.console=%green[%d{yyyy-MM-dd HH:mm:ss} %blue(%-5level)] %red([%thread]) %yellow(%logger{36}) - %msg%n

## -------gemini---------
## This works on the gemini api key and gemini dependency
spring.ai.google.genai.api-key=${OPEN_API_KEY}

## -------ollama---------
### If you face error mistral based llm
# spring.ai.model.chat=ollama
spring.ai.ollama.chat.model=llama3.2:1b

### Added to connect with ollama server running on another local machine
spring.ai.ollama.base-url=${IP_ADDRESS}:11434

## -------openai for docker gemma3---------
spring.ai.openai.chat.model=ai/gemma3
spring.ai.openai.chat.base-url=${IP_ADDRESS}:12434/engines/v1
spring.ai.openai.api-key=dummy

## -------openai for docker embedding model---------
spring.ai.openai.embedding.base-url=${IP_ADDRESS}:12434/engines/v1
spring.ai.openai.embedding.model=ai/mxbai-embed-large

# Spring AI auto-disables the ChatClient.Builder bean when multiple ChatModel beans exist (as we have here: OpenAI + Ollama).
# Setting this to true overrides that and re-enables ChatClient.Builder autoconfiguration anyway.
# By default, it is true
#spring.ai.chat.client.enabled=false

debug=true

# This is used for debugging advisor behavior
logging.level.org.springframework.ai.chat.client.advisor=DEBUG


###########################################
#										  #
#			    H2 Database               #
#										  #
###########################################
#spring.datasource.url=jdbc:h2:mem:h2db

# To persist data in a file
spring.datasource.url=jdbc:h2:file:C:/Users/bsara/h2db/springAI
#spring.datasource.url=jdbc:h2:file:./h2DBdata/springAi
#spring.datasource.url=jdbc:h2:file:~/chatmemory;AUTO_SERVER=true
# Set the same url in browser url - jdbc:h2:file:/resources/data
spring.datasource.username=sa
spring.datasource.password=sa

## We have sql file here
## spring-ai-model-chat-memory-repository-jdbc-2.0.0.jar!\org\springframework\ai\chat\memory\repository\jdbc\schema-h2.sql
## spring-ai-model-chat-memory-repository-jdbc-2.0.0.jar!\org\springframework\ai\chat\memory\repository\jdbc\schema-postgresql.sql
#Old Driver
#spring.datasource.driverClassName=org.h2.Driver
spring.datasource.driver-class-name=org.h2.Driver
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

#spring.jpa.open-in-view=false

# H2 console http://localhost:8080/h2-console
# We need this dependency to use the bellow properties
# implementation 'org.springframework.boot:spring-boot-h2console:4.0.0-M1'
# Enable the H2 web console (disabled by default for security)
spring.h2.console.enabled=true

# URL path to access the console in the browser
spring.h2.console.path=/h2-console
# Console path console http://localhost:8080/h2 We are changing the default path
# spring.h2.console.path=/h2

spring.h2.console.settings.trace=false

# Allow access when running behind a reverse proxy or from non-localhost
spring.h2.console.settings.web-allow-others=false

spring.ai.chat.memory.repository.jdbc.initialize-schema=always

# No need of this from spring ai 2.0
#spring.ai.chat.memory.repository.jdbc.schema=classpath:/schema/schema-h2db.sql

############################
#                          #
# Common attributes for DB #
#                          #
############################
#spring.jpa.show-sql=true
#  https://stackoverflow.com/q/36605104/11962586
# Stops auto deletion of inserted values in database, # Options - none, create
#spring.jpa.hibernate.ddl-auto=update

spring.docker.compose.stop.command=down

spring.ai.vectorstore.qdrant.initialize-schema=true
spring.ai.vectorstore.qdrant.host=localhost
# For gRPC protocol
spring.ai.vectorstore.qdrant.port=6334
spring.ai.vectorstore.qdrant.collection-name=sarath-spring-ai
spring.ai.model.embedding=openai
# prevent Spring Boot from auto-creating the QdrantVectorStore bean
#spring.ai.vectorstore.qdrant.enabled=false





