spring.application.name=springboot-ai
logging.pattern.console=%green[%d{yyyy-MM-dd HH:mm:ss} %blue(%-5level)] %red([%thread]) %yellow(%logger{36}) - %msg%n

## -------gemini---------
## This works on the gemini api key and gemini dependency
#spring.ai.google.genai.api-key=${OPEN_API_KEY}

## -------ollama---------
### If you face error mistral based llm
#spring.ai.model.chat=ollama
#spring.ai.ollama.chat.model=llama3.2

### Added to connect with ollama server running on another local machine
#spring.ai.ollama.base-url=${IP_ADDRESS}:11434

## -------openai for docker gemma3---------
spring.ai.openai.chat.model=ai/gemma3
spring.ai.openai.chat.base-url=${IP_ADDRESS}:12434/engines/v1
spring.ai.openai.api-key=dummy