spring.application.name=springboot-ai
logging.pattern.console=%green[%d{yyyy-MM-dd HH:mm:ss} %blue(%-5level)] %red([%thread]) %yellow(%logger{36}) - %msg%n


## This works on the gemini api key and gemini dependency
#spring.ai.google.genai.api-key=${OPEN_API_KEY}

## If you face error mistral based llm
spring.ai.model.chat=ollama
spring.ai.ollama.chat.model=llama3.2